services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: python_boilerplate_local_django
    container_name: python_boilerplate_local_django
    platform: linux/x86_64
    depends_on:
      - mariadb
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start
    networks:
      - python_boilerplate_app

  mariadb:
    container_name: python_boilerplate_local_mariadb
    image: 'mariadb:10.7'
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-secret}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-python_boilerplate}
    volumes:
      - 'localmariadb:/var/lib/mysql'
    networks:
      - python_boilerplate_app

  mailhog:
    container_name: python_boilerplate_local_mailhog
    restart: unless-stopped
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025 
    networks:
      - python_boilerplate_app

  selenium:
    container_name: python_boilerplate_local_selenium
    image: 'selenium/standalone-chrome'
    environment:
        - SE_NODE_MAX_SESSIONS=1
        - SE_NODE_OVERRIDE_MAX_SESSIONS=true
        - START_XVFB=false
    ports:
        - '4444:4444'
    volumes:
        - '/dev/shm:/dev/shm'
    networks:
      - python_boilerplate_app

networks:
  python_boilerplate_app:
    driver: bridge

volumes:
  localmariadb:
    driver: local
