"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import logging.config
import os
import time
from pathlib import Path

import environ

env = environ.Env(
    DEBUG=(bool, False),
    CONNECTION=(str, None),
    APP_ENV=(str, ""),
    MAILGUN_SECRET=(str, ""),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE_PATH = os.path.join(BASE_DIR, ".env")
if os.path.exists(ENV_FILE_PATH):
    environ.Env.read_env(ENV_FILE_PATH)

APP_ENV = env("APP_ENV")
IS_PRODUCTION = APP_ENV.lower() in {"prod", "production"}
APP_URL = env("APP_URL", default="http://localhost:8000")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env("ALLOWED_HOSTS", cast=lambda value: value.split())
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

SITE_ID = 1

THIRD_PARTY_APPS = [
    "corsheaders",
    "django_extensions",
]

LOCAL_APPS = [
    "app",
    "seleniumpy",
]

INSTALLED_APPS = LOCAL_APPS + DJANGO_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "app.middleware.RequestLogMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "app.middleware.AdminRateLimitMiddleware",
]

CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS", cast=lambda value: value.split())

ROOT_URLCONF = "app.urls"

CORS_URLS_REGEX = r"^/api/.*$"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if env.str("CONNECTION") is None or env.str("CONNECTION") == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env("MARIADB_DATABASE"),
            "USER": env("MARIADB_USER"),
            "PASSWORD": env("MARIADB_PASSWORD"),
            "HOST": env("MARIADB_HOST"),
            "PORT": env("MARIADB_PORT"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = []
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


class BracketLocationFormatter(logging.Formatter):
    def __init__(self, format=None, datefmt=None, style="%", validate=True, **kwargs):
        super().__init__(fmt=format, datefmt=datefmt, style=style, validate=validate)

    def format(self, record):
        record.location = f"[{record.name}:{record.lineno}]"
        return super().format(record)


LOG_LEVEL = env("LOG_LEVEL", default="DEBUG" if not IS_PRODUCTION else "INFO").upper()
LOGS_DIR = env("LOGS_DIR", default=os.path.join(BASE_DIR, "logs"))
LOG_FILE_PATH = env(
    "DJANGO_LOG_FILE",
    default=os.path.join(LOGS_DIR, "django_app.log"),
)
os.makedirs(os.path.dirname(LOG_FILE_PATH), exist_ok=True)

logging.config.dictConfig(
    {
        "version": 1,
        # Setting this to False stops Django from silencing your custom logs
        "disable_existing_loggers": False,
        "formatters": {
            "atomic_utc": {
                "()": BracketLocationFormatter,
                "format": "[%(asctime)s] %(levelname)-8s %(location)-32s %(message)s",
                "datefmt": "%Y-%m-%d %H:%M:%S %Z",
            },
        },
        "handlers": {
            "file": {
                "level": LOG_LEVEL,
                "class": "logging.FileHandler",
                "filename": LOG_FILE_PATH,
                "formatter": "atomic_utc",
            },
        },
        "root": {
            "handlers": ["file"],
            "level": LOG_LEVEL,
        },
    }
)

# UTC time for logging timestamps
logging.Formatter.converter = time.gmtime

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_USE_TLS = env("EMAIL_USE_TLS") == "True"
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = "info@django-app.com"

MAILGUN_DOMAIN = env("MAILGUN_DOMAIN")
MAILGUN_SECRET = env("MAILGUN_SECRET")
MAIL_TO_ADDRESS = env("MAIL_TO_ADDRESS")
MAIL_FROM_ADDRESS = env("MAIL_FROM_ADDRESS")
MAIL_SUBJECT = env("MAIL_SUBJECT")

# Security defaults keep local development easy while hardening production.
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=IS_PRODUCTION)
# HSTS should stay 0 outside production; increase gradually in production rollouts.
SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS", default=31536000 if IS_PRODUCTION else 0
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=IS_PRODUCTION,
)
# Preload only when the whole domain tree is permanently HTTPS-only.
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=IS_PRODUCTION)
SECURE_CONTENT_TYPE_NOSNIFF = env.bool("SECURE_CONTENT_TYPE_NOSNIFF", default=True)
X_FRAME_OPTIONS = env("X_FRAME_OPTIONS", default="DENY")
SECURE_REFERRER_POLICY = env("SECURE_REFERRER_POLICY", default="same-origin")

# Only trust X-Forwarded-Proto when explicitly enabled
USE_X_FORWARDED_PROTO = env.bool("USE_X_FORWARDED_PROTO", default=False)
if USE_X_FORWARDED_PROTO:
    # Tuple assignment is correct here
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SELENIUM_HEADLESS = env.bool('SELENIUM_HEADLESS', default=False)
